"use client";

import { useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { Bot, Calendar, CheckSquare, Cloud, Mail, Sparkles } from "lucide-react";
import Link from "next/link";

import { AICore } from "@/components/ai-core/ai-core";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { LoadingState } from "@/components/ui/state";
import { api } from "@/lib/api";

function greeting(): string {
  const hour = new Date().getHours();
  if (hour < 12) return "Good morning, Dr. Opara.";
  if (hour < 18) return "Good afternoon, Dr. Opara.";
  return "Good evening, Dr. Opara.";
}

export default function HomePage() {
  const status = useQuery({
    queryKey: ["system", "status"],
    queryFn: api.system.status,
    refetchInterval: 10_000,
  });

  const usage = useQuery({
    queryKey: ["system", "usage"],
    queryFn: api.system.usage,
    refetchInterval: 10_000,
  });

  const email = useQuery({
    queryKey: ["email", "unread"],
    queryFn: api.email.unread,
    refetchInterval: 30_000,
  });

  const today = useQuery({
    queryKey: ["calendar", "today"],
    queryFn: api.calendar.today,
    refetchInterval: 60_000,
  });

  const weather = useQuery({
    queryKey: ["weather", "current"],
    queryFn: api.weather.current,
    refetchInterval: 300_000,
  });

  const briefing = useQuery({
    queryKey: ["briefing"],
    queryFn: api.briefing.get,
    staleTime: 5 * 60_000,
  });

  const stats = [
    { label: "Conversation turns", value: usage.data?.conversation_turns ?? "—", icon: Bot },
    { label: "Memories stored", value: usage.data?.memories_stored ?? "—", icon: Sparkles },
    { label: "Pending tasks", value: usage.data?.tasks_pending ?? "—", icon: CheckSquare },
    {
      label: "Unread email",
      value: email.data?.configured ? email.data.messages.length : "—",
      icon: Mail,
    },
  ];

  return (
    <div className="mx-auto max-w-6xl px-4 py-8 md:px-8">
      <div className="flex flex-col items-start justify-between gap-6 md:flex-row md:items-center">
        <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="text-2xl font-semibold tracking-tight text-[var(--foreground)] text-glow">
            {greeting()}
          </h1>
          <p className="mt-1 text-sm text-[var(--muted)]">
            Here is what Victoria is tracking right now.
          </p>
        </motion.div>
        <AICore
          state={status.isError ? "offline" : "idle"}
          size={88}
          label={status.isError ? "Offline" : "Systems nominal"}
        />
      </div>

      <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((stat, index) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.05 }}
          >
            <Card>
              <CardContent className="flex items-center justify-between pt-5">
                <div>
                  <p className="text-xs text-[var(--muted)]">{stat.label}</p>
                  <p className="mt-1 text-2xl font-semibold text-[var(--foreground)]">
                    {stat.value}
                  </p>
                </div>
                <stat.icon className="size-5 text-[var(--accent)]" />
              </CardContent>
            </Card>
          </motion.div>
        ))}
      </div>

      <div className="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Executive briefing</CardTitle>
            <CardDescription>Generated by Victoria just now</CardDescription>
          </CardHeader>
          <CardContent>
            {briefing.isLoading && <LoadingState label="Victoria is preparing your briefing…" />}
            {briefing.isError && (
              <p className="text-sm text-[var(--danger)]">
                Could not generate a briefing right now.
              </p>
            )}
            {briefing.data && (
              <p className="whitespace-pre-line text-sm leading-relaxed text-[var(--foreground)]/90">
                {briefing.data.briefing}
              </p>
            )}
          </CardContent>
        </Card>

        <div className="flex flex-col gap-4">
          <Card>
            <CardHeader className="flex-row items-center justify-between space-y-0">
              <CardTitle className="flex items-center gap-2">
                <Calendar className="size-4 text-[var(--accent)]" /> Today
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {today.data?.events.length ? (
                today.data.events.map((event) => (
                  <div key={event.id} className="text-sm">
                    <p className="font-medium text-[var(--foreground)]">{event.title}</p>
                    <p className="text-xs text-[var(--muted)]">
                      {new Date(event.start_time).toLocaleTimeString([], {
                        hour: "numeric",
                        minute: "2-digit",
                      })}
                    </p>
                  </div>
                ))
              ) : (
                <p className="text-sm text-[var(--muted)]">Nothing on the calendar today.</p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex-row items-center justify-between space-y-0">
              <CardTitle className="flex items-center gap-2">
                <Cloud className="size-4 text-[var(--accent)]" /> Weather
              </CardTitle>
              {weather.data && (
                <Badge variant={weather.data.configured ? "success" : "outline"}>
                  {weather.data.configured ? "Live" : "Not connected"}
                </Badge>
              )}
            </CardHeader>
            <CardContent>
              {weather.data?.configured ? (
                <div className="text-sm">
                  <p className="text-2xl font-semibold text-[var(--foreground)]">
                    {weather.data.temperature_f}&deg;F
                  </p>
                  <p className="text-[var(--muted)]">
                    {weather.data.description}, feels like {weather.data.feels_like_f}&deg;F
                  </p>
                </div>
              ) : (
                <p className="text-sm text-[var(--muted)]">
                  Set <code>WEATHER_API_KEY</code> to connect a forecast.
                </p>
              )}
            </CardContent>
          </Card>
        </div>
      </div>

      <Card className="mt-6">
        <CardHeader>
          <CardTitle>Quick actions</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-wrap gap-x-6 gap-y-2 text-sm">
          <Link className="text-[var(--muted)] transition-colors hover:text-[var(--accent)]" href="/assistant">
            Talk to Victoria &rarr;
          </Link>
          <Link className="text-[var(--muted)] transition-colors hover:text-[var(--accent)]" href="/tasks">
            Review tasks &rarr;
          </Link>
          <Link className="text-[var(--muted)] transition-colors hover:text-[var(--accent)]" href="/email">
            Check email &rarr;
          </Link>
          <Link className="text-[var(--muted)] transition-colors hover:text-[var(--accent)]" href="/memory">
            What Victoria remembers &rarr;
          </Link>
          <Link className="text-[var(--muted)] transition-colors hover:text-[var(--accent)]" href="/knowledge">
            Search your documents &rarr;
          </Link>
        </CardContent>
      </Card>
    </div>
  );
}
